language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
deploy:
  provider: heroku
  api_key: 965f3cec-c80e-438d-ade1-47511b7f3c72
  run: "python db/models.py"
  app: glacial-scrubland-6807
# command to run tests
script: nosetests