language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
deploy:
  provider: heroku
  api_key: glacial-scrubland-6807
  app:
    master: orgeventos