language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
deploy:
  provider: heroku
  api_key: 090b2e41-de41-4c8d-9f6b-cc7d3a29f196
  app: glacial-scrubland-6807
# command to run tests
script: nosetests